name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-ci:
    uses: CharlesJS/shared-workflows/.github/workflows/ci.yml@allow-root
    with: 
      run_as_root: true
      setup_filesystems: true
